name: Update Changelog

env:
  GEM_HOME: ~/gems

on:
  schedule:
    # Will run at 01:00 on the 1st of every month 
    - cron: "30 1 1 * *"
  workflow_dispatch:

concurrency:
  group: update-changelog
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: "Update CHANGELOG.md"
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gem install github_changelog_generator
      - name: "Commit CHANGELOG.md"
        run: |
          github_changelog_generator -u skywinder -p ActionSheetPicker-3.0
          git add CHANGELOG.md
          if [ ! -n "$(git status -s)" ]; then
            echo "NOTHING TO COMMIT"
          else
            git config user.name "${GITHUB_ACTOR}"
            git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            git commit -m "Update CHANGELOG.md"
            git push --no-verify
          fi
